const express = require('express');
const router = express.Router();


const courses = require('./courses');
const movies = require('./movies');
const people = require('./people');
const genres = require('./genres');
const customers = require('./customer');
const login = require('./login');
const branch = require('./branch');
const seatType = require('./price/seatType');
const playType = require('./price/playType');
const cinema = require('./cinema');
const seats = require('./seats');
const schedule = require('./schedule');
const book_seat = require('./book_seat');
const ticket = require('./ticket');
const payMethod = require('./payMethod');
const discount = require('./discount');
router.use('/api/customer', customers);
router.use('/api/courses', courses);
router.use('/api/movies', movies);
router.use('/api/genres', genres);
router.use('/api/people', people);
router.use('/api/login', login);
router.use('/api/branch', branch);
router.use('/api/playType', playType);
router.use('/api/seatType', seatType);
router.use('/api/cinema', cinema);
router.use('/api/seats', seats);
router.use('/api/schedule', schedule);
router.use('/api/book_seat', book_seat);
router.use('/api/ticket', ticket);
router.use('/api/payMethod', payMethod);
router.use('/api/discount', discount);
module.exports = router;